# Generated by Django 3.0.3 on 2020-03-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='uploads/avatars/no_avatar.png', upload_to='uploads/avatars/'),
        ),
    ]
